version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@34.47.181.15:5672//
      - CELERY_RESULT_BACKEND=rpc://
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery-worker:
    build: .
    depends_on:
      - fastapi-app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@34.47.181.15:5672//
      - CELERY_RESULT_BACKEND=rpc://
    command: celery -A app.tasks worker --loglevel=info
